name: "Label this pull request"

on:
  pull_request:
    types: [opened, edited]

jobs:
  build-docker-base-package:
    runs-on: ubuntu-latest
    #
    # do not run on forks
    #
    if: github.repository_owner == 'wanjohiryan'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - uses: github/issue-labeler@v2.6 #Label based on regex
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/label-regex.yml
          not-before: 2023-01-30T02:54:32Z
          enable-versioned-regex: 0
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"