name: "Push image to Docker Hub"

on:
  push:
    branches: [ main ]
  #
  # Run this action periodically to keep docker up-to-date
  # even if there is no activity in this repo.
  #
  schedule:
    - cron: "5 0 * * THU" #every thursday
  # run it during pull request

jobs:
  build-docker-base-package:
    runs-on: ubuntu-latest
    #
    # do not run on forks
    #
    if: github.repository_owner == 'wanjohiryan'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: .docker/base/Dockerfile
          push: true
          tags: wanjohiryan/warp:h264
  build-docker-chrome:
    needs: build-docker-base-package
    runs-on: ubuntu-latest
    #
    # do not run on forks
    #
    if: github.repository_owner == 'wanjohiryan'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: examples/h264-chrome/Dockerfile
          push: true
          tags: wanjohiryan/warp:chrome-h264