name: "Test go package"

# Simple workflow to test go. Works with errorrs tho :)
#!FIXME: Start writing go tests.
#

on:
  pull_request:
  #
  # Run this action periodically to keep docker up-to-date
  # even if there is no activity in this repo.
  #
  schedule:
    - cron: "5 0 * * 1-7" #every thursday
  # run it during pull request

jobs:
  test-go:
    strategy:
      matrix: 
        go-version: [1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest] #test on Windows also, for development compatibility
    runs-on: ${{matrix.os}}
    #
    # do not run on forks
    #
    if: github.repository_owner == 'wanjohiryan'
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Run main.go
        run: go run main.go
