name: Create and test docker image
#TODO: find a way to log errors from docker container onto github

on:
  pull_request:

jobs:
  build-go:
    name: Build go binary
    runs-on: ubuntu-latest
    steps: 
      -
        name: Checkout repo
        uses: actions/checkout@v3
      - 
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      #TODO: Find a way to test this before building
      - 
        name: Build binary
        run: go build -v ./
      -
       name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
         name: gobinary
         path: ./warp
  build-certs:
    name: Build self-signed certs
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Install mkcert
        run: |
          set -o pipefail
          
          apt-get update; \
          wget -nv -O /usr/local/bin/mkcert https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64; \
          chmod +x /usr/local/bin/mkcert;

        shell: bash
      - 
        name: Install mkcert
        run: |
          set -o pipefail

          mkdir ./certs && cd ./certs
          
          mkcert -cert-file localhost.crt -key-file localhost.key localhost 127.0.0.1 ::1
        
        shell: bash
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: certs
          path: ./certs

  build-docker-nvidia:
      name: Build nvidia base image
      needs: 
        - build-go
        - build-certs
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        -
          name: Download go binary
          uses: actions/download-artifact@v3
          with:
            name: gobinary
            path: ./
        -
          name: Download certs folder
          uses: actions/download-artifact@v3
          with:
            name: certs
            path: ./
        - 
          name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
        - 
          name: Build Docker image
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: docker/nvidia/Dockerfile
            push: false
            load: true
            tags: warp:nvenc
        - 
          name: Run Docker Container
          #error code 124 is timeout error
          run: |
            set -o pipefail
            output=$(timeout 2m docker run warp:nvenc 2>&1) || exitcode=$?

            if [[ $exitcode != 0 && $exitcode != 124 ]]; then
              echo "$output"
              exit $exitcode
            else 
              echo "$output"
             echo -e "\033[01;34mDocker run successful\033[0m"
              exit 0
            fi
          shell: bash
