name: Create and test docker image
#TODO: find a way to log errors from docker container onto github

on:
  pull_request:

jobs:
  build-docker-base:
      name: Build docker image for testing
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        
        - 
          name: Build docker image and clean up
          run: |
            cp .docker/x264-base/Dockerfile .
            docker build -t wanjohiryan/warp:x264 .
            rm Dockerfile 
        - 
          name: Build docker image for chrome
          run: |
            cp examples/chrome-x264/Dockerfile .
            docker build -t wanjohiryan/warp:chrome-x264 --build-arg WARP_IMAGE=wanjohiryan/warp:x264  .