name: Create and test docker image
#TODO: find a way to log errors from docker container onto github

on:
  pull_request:

jobs:
  build-docker-base:
      name: Build base image
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        
        - 
          name: Build and run warp docker
          run: bash ${GITHUB_WORKSPACE}/build.sh
  
  build-firefox-example:
      name: Build firefox
      needs: build-docker-base
      runs-on: ubuntu-latest
      steps:
      - 
        name: Checkout repo
        uses: actions/checkout@v3
      - 
        name: Build and run firefox docker
        run: bash ${GITHUB_WORKSPACE}/build-example.sh