name: Create and test docker image
#TODO: find a way to log errors from docker container onto github
#TODO: find a way to test client and server before running the docker container, seems effective in catching any errors
on:
  pull_request:

jobs:
  build-docker-base:
      name: Build docker image for testing
      runs-on: ubuntu-latest
              
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        
        - 
          name: Build docker image and clean up
          run: |
            cp .docker/base/Dockerfile .
            docker build -t wanjohiryan/warp:h264 .
            rm Dockerfile 
  
  build-chrome-example:
      name: Build docker example for testing
      runs-on: ubuntu-latest
      needs: build-docker-base
              
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        
        - 
          name: Build docker image
          run: |
            cp examples/h264-chrome/Dockerfile .
            docker build -t wanjohiryan/warp:chrome-h264 .