name: Create and test docker image
#TODO: find a way to log errors from docker container onto github

on:
  pull_request:

jobs:
  build-docker-base:
      name: Build base image
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        - 
          name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
        - 
          name: Build Docker image
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: .docker/base/Dockerfile
            push: false
            load: true
            tags: wanjohiryan/warp:latest
        - 
          name: Run Docker Container
          id: run-container
          run: |
            set -o pipefail
            docker run wanjohiryan/warp:x264 &

            sleep 20
            kill %?docker

            exit 0
          shell: bash

  build-brave-example:
      name: Build brave browser
      needs: build-docker-base
      runs-on: ubuntu-latest
      steps:
      - 
        name: Checkout repo
        uses: actions/checkout@v3
      - 
          name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
      - 
        name: Build Docker example
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: examples/brave/Dockerfile
          push: false
          load: true
          tags: wanjohiryan/warp:brave-x264
      - 
        name: Run Docker Container example
        id: run-container
        run: |
          set -o pipefail
          docker run wanjohiryan/brave-x264 &

          sleep 20
          
          kill %?docker
          exit 0
        shell: bash