name: Create and test docker image
#TODO: find a way to log errors from docker container onto github

on:
  pull_request:

jobs:
  auto-label-prs:
      name: Build docker image for testing
      runs-on: ubuntu-latest
              
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        
        - 
          name: Build docker image and clean up
          run: |
            cp .docker/x264-base/Dockerfile .
            docker build -t wanjohiryan/warp:x264 .
            rm Dockerfile 
  
  build-chrome-example:
      name: Build docker example for testing
      runs-on: ubuntu-latest
      needs: build-docker-base
              
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        
        - 
          name: Build docker image
          run: |
            cp examples/chrome-x264/Dockerfile .
            docker build -t wanjohiryan/warp:chrome-x264 .