name: Create and test docker image
#TODO: find a way to log errors from docker container onto github

on:
  pull_request:

jobs:
  build-docker-base:
      name: Build docker image for testing
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        
        - 
          name: Build docker image and clean up
          run: |
            cp .docker/base/Dockerfile .
            docker build -t wanjohiryan/warp:x264 .
            rm Dockerfile 
        - 
          name: Run base docker image
          run: |
            docker run wanjohiryan/warp:x264