name: Build client exe and docker relay server

on:
  pull_request:
    paths-ignore:
      - '.github/**'
# Cancel previous runs of the same workflow on the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build-docker-relay:
      name: Build relay server for moq-rs
      runs-on: ubuntu-latest
      defaults:
        run:
            working-directory: moq-server
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
          with:
            submodules: recursive
        - 
          name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v3
        - 
          name: Build Docker image
          uses: docker/build-push-action@v5
          with:
            context: ./
            file: Dockerfile
            push: false
            load: true
            tags: warp:relay