name: Build docker

on:
  pull_request:

jobs:
  build-cargo-windows:
    name: Build rust code on windows
    runs-on: windows-latest
    steps: 
      -
        name: Checkout repo
        uses: actions/checkout@v3
      - 
        name: Setup Rust
        uses:  hecrj/setup-rust-action@v2
        with:
          rust-version: stable
      -
        name: Build 
        run: cargo build --release

  build-cargo-ubuntu:
    name: Build rust code on ubuntu
    runs-on: ubuntu-latest
    steps: 
      -
        name: Checkout repo
        uses: actions/checkout@v3
      - 
        name: Setup Rust
        uses:  hecrj/setup-rust-action@v2
        with:
          rust-version: stable
      -
        name: Build 
        run: cargo build --release

  build-docker-nvidia:
      name: Build base image
      needs:
        - build-cargo-ubuntu
        - build-cargo-windows
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        - 
          name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
        - 
          name: Build Docker image
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: docker/base/Dockerfile
            push: false
            load: true
            tags: warp:base
