name: Build docker

on:
  pull_request:
  # push:
  #   paths-ignore:
  #     - '.github/**'
  #     #much of the time it does not affect docker builds
  #     - 'internal/ui/**'

jobs:
  build-docker-nvidia:
      name: Build base image
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        - 
          name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
        - 
          name: Build Docker image
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: docker/base/Dockerfile
            push: false
            load: true
            tags: warp:base
        # - 
        #   name: Run Docker Container
        #   #error code 124 is timeout error
        #   run: |
        #     set -o pipefail
        #     output=$(timeout 2m docker run warp:nvenc 2>&1) || exitcode=$?

        #     if [[ $exitcode != 0 && $exitcode != 124 ]]; then
        #       echo "$output"
        #       exit $exitcode
        #     else 
        #       echo "$output"
        #      echo -e "\033[01;34mDocker run successful\033[0m"
        #       exit 0
        #     fi
        #   shell: bash
