name: Release

on:
  # workflow_dispatch:
    push:



# NOTE: For Linux builds, we can only build with Ubuntu. It should be the oldest base system we intend to support. See PR-759 & https://tauri.app/v1/guides/building/linux for reference.

jobs:
  build-warp:
    defaults:
      run:
          working-directory: moq-server
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            bundles: dmg
          - host: macos-latest
            target: aarch64-apple-darwin
            bundles: dmg
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            bundles: msi
          # - host: windows-latest
          #   target: aarch64-pc-windows-msvc
          - host: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bundles: appimage
          # - host: ubuntu-20.04
          #   target: x86_64-unknown-linux-musl
          # - host: ubuntu-20.04
          #   target: aarch64-unknown-linux-gnu
          # - host: ubuntu-20.04
          #   target: aarch64-unknown-linux-musl
          # - host: ubuntu-20.04
          #   target: armv7-unknown-linux-gnueabihf
    name: Warp for ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Rust
        id: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false
          prefix-key: 'v0-rust-deps'
          shared-key: ${{ matrix.settings.target }}

      - name: Build
        run: cargo build --target ${{ matrix.settings.target }} --manifest-path ./moq-pub/Cargo.toml --release
      
      - name: Copy and rename artifacts (Linux)
        if: ${{ matrix.settings.host == 'ubuntu-20.04' }}
        run: |
          cp target/${{ matrix.settings.target }}/release/moq-pub ./warp
      
      - name: Copy and rename artifacts (Windows)
        if: ${{ matrix.settings.host == 'windows-latest' }}
        run: |
          cp "target/${{ matrix.settings.target }}/release/moq-pub.exe" ./warp.exe
          
      - name: Copy and rename artifacts (macOS)
        if: ${{ matrix.settings.host == 'macos-latest' }}
        run: |
          cp target/${{ matrix.settings.target }}/release/moq-pub ./warp

      - name: Publish artifacts (Windows)
        if: ${{ matrix.settings.host == 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: Warp-${{ matrix.settings.target }}
          path: ./warp.exe
          if-no-files-found: error
          retention-days: 5
      
      - name: Publish artifacts (Windows)
        if: ${{ matrix.settings.host != 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: Warp-${{ matrix.settings.target }}
          path: ./warp
          if-no-files-found: error
          retention-days: 5