name: Compile and Push Changes

on:
    pull_request:
    push:
      paths:
        - internal/ui/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - 
      name: Install packages
      run: |
        cd internal/ui
        npm install
    - 
      name: Build project
      run: |
        cd internal/ui
        npm run build
    - 
      name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Built new nodejs UI'
        commit_options: '--no-verify'
